# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Jekyll-base
description:
tagline:
url: http://astir.ninja

source: src
destination: serve
