---
en:
  0:
    variantClasses: "odd grey-background crown-corks__item crown-corks__item--first"
    title: "White Primer"
    title_variantClasses: "title--large"
    subtitle: "PRIMER"
    counter:  "01"
    body: "White enamel lacquer is mainly used on top of TFS steel. It allows colours to reach a bright and glossy look and gives a pure white appearance. Most Pantone references can be achieved using White enamel."
    bgImage: "/images/corks/Primer-Back.jpg"
    bgImagePosition: "left top"
    bgImageSize: "60% auto"
    id: "white-primer"
    group: "primer"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Primer-White.png"
    includeArea: "crown/white-primer.html"
  1:
    variantClasses: "grey-background crown-corks__item"
    title: "Transparent Primer"
    title_variantClasses: "title--large"
    subtitle: "PRIMER"
    counter: "02"
    body: "Clear size substrate. It improves colour adhesion to the steel plates, hence always applied to TFS and ETP steel, when metallic appearance is requested."
    id: "transparent-primer"
    group: "primer"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Primer-Transparent.jpg"
    includeArea: "crown/primertransparent.html"
  2:
    variantClasses: "odd grey-background crown-corks__item"
    title: "Aluminum"
    title_variantClasses: "title--large"
    subtitle: "PRIMER"
    counter: "03"
    body: "Aluminum size primer unifies the surface finish with a constant aluminum shade look. It is used instead of white lacquer or clear size and also provides excellent adhesion to the applied colours."
    id: "aluminum-primer"
    group: "primer"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Primer-Aluminium.jpg"
    includeArea: "crown/primeraluminium.html"
  3:
    variantClasses: "odd crown-corks__item crown-corks__item--first"
    title: "Offset Print"
    title_variantClasses: "title--large"
    subtitle: "PRINT"
    counter: "01"
    body: "We can meet most of pantone references on crowns, especially if white base is applied and use Solid Coated as a reference guide. We can even meet your colour target tonality by sending us a sample or a label. We use sophisticated devices and software to allow us to mix internally and create thousands of different colour references."
    bgImage: "/images/corks/Print-Back.jpg"
    bgImagePosition: "left top"
    bgImageSize: "60% auto"
    buttonText: "DOWNLOAD PRINT SPEC"
    buttonLink: "/pdfs/specifications.pdf"
    buttonClasses: "btn-primary"
    id: "offset-print"
    group: "print"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Print-offset.png"
    includeArea: "crown/pantone.html"
  4:
    variantClasses: "crown-corks__item"
    title: "CMYK"
    title_variantClasses: "title--large"
    subtitle: "PRINT"
    counter: "02"
    body: "Anything you imagine can be printed in the small crown surface area, using CMYK process printing. We generate fully customized designs including images, photos, faces and any type of fancy prints."
    id: "cmyk-print"
    group: "print"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Print-CMYK.jpg"
    includeArea: "crown/cmyk.html"
  5:
    variantClasses: "odd crown-corks__item"
    title: "Cold Activated Ink"
    title_variantClasses: "title--large"
    subtitle: "PRINT"
    counter: "03"
    body: "Thermocromic ink changes colours when your beer or beverage is cold enough and ready to drink. This interactive special effect clearly indicates that the product has reached the right temperature, improving the overall drinking experience."
    id: "cold-activated-print"
    group: "print"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Print-Cold-activated.jpg"
    includeArea: "crown/coldactivated.html"
  6:
    variantClasses: "grey-background crown-corks__item crown-corks__item--first"
    title: "Lithographic Print"
    title_variantClasses: "title--large"
    subtitle: "INTERNAL PRINT"
    body: "Printed crowns help build a strong marketing strategy and customer engagement. We use litho printing to create promotional crown corks with prints under the steel sheet. A number of promo options are available: specific messages, gifts or quotes etc."
    bgImage: "/images/corks/Unique-codes-back.jpg"
    bgImagePosition: "left top"
    bgImageSize: "70 auto"
    id: "internal-print"
    group: "internal-print"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Internal-Print.png"
    includeArea: "crown/lithographic.html"
  7:
    variantClasses: "odd crown-corks__item crown-corks__item--first"
    title: "Internal Varnish"
    title_variantClasses: "title--large"
    subtitle: "INTERIOR SIDE"
    body: "Internal varnish is applied to all printed sheets in order to allow liner adhesion to the crown shell. It also protects the internal side of the crown cap from corrosion and scratching during the bottling process. There are different types of internal varnish depending on the application."
    bgImage: "/images/corks/Interior-Side-Back.jpg"
    bgImagePosition: "left top"
    bgImageSize: "75% auto"
    id: "interior-side"
    group: "interior-side"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Interior-varnish.png"
    includeArea: "crown/internalvarnish.html"
  8:
    variantClasses: "grey-background  crown-corks__item crown-corks__item--first"
    title: "Unique Promotional Codes"
    title_variantClasses: "title--large"
    subtitle: "INJECT COATING"
    body: "Enhance consumer interaction with lottery promotions by printing unique alphanumeric codes under the liner. Our in-house developed software algorithm generates unique codes that are applied with an inkjet head on each crown cork. FDA compliant ink is used in every application."
    bgImage: "/images/corks/Anatomy-Back.jpg"
    bgImagePosition: "left top"
    bgImageSize: "60% auto"
    id: "inject-coating"
    group: "inject-coating"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Unique-Promotional-Codes.png"
    includeArea: "crown/promocodes.html"
  9:
    variantClasses: "odd crown-corks__item crown-corks__item--first"
    title: "Pry Off"
    title_variantClasses: "title--large"
    subtitle: "INTERIOR PLASTIC LINER"
    counter: "01"
    body: "Enhance consumer interaction with lottery promotions by printing unique alphanumeric codes under the liner. Our in-house developed software algorithm generates unique codes that are applied with an inkjet head on each crown cork. FDA compliant ink is used in every application."
    bgImage: "/images/corks/Interior-Plastic-Liner-Back.jpg"
    bgImagePosition: "left top"
    bgImageSize: "70% auto"
    id: "pry-off-interior"
    group: "interior-liner"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Interior-pry-off.png"
    includeArea: "crown/pryoff.html"
  10:
    variantClasses: " crown-corks__item"
    title: "Twist Off"
    title_variantClasses: "title--large"
    subtitle: "INTERIOR PLASTIC LINER"
    counter: "02"
    body: "A single lip liner profile, mainly used in USA and Canada. Doesn’t need bottle opener but requires extra lubricated and softer type of liner to meet the opening torque specs. Most common profiles are 917 and 912."
    id: "twist-off-interior"
    group: "interior-liner"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Interior-twist-off.jpg"
    includeArea: "crown/twistoff.html"
  11:
    variantClasses: "odd crown-corks__item"
    title: "Oxygen Scavenger"
    title_variantClasses: "title--large"
    subtitle: "INTERIOR PLASTIC LINER"
    counter: "03"
    body: "A special liner that absorbs the oxygen remaining in the bottle neck finish, decreasing the beer or beverage oxidation. Oxygen scavenger liners provide extra freshness, better taste and extended shelf life. That’s why they are strongly preferred by premium beer brands and craft breweries"
    id: "oxygen-interior"
    group: "interior-liner"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Interior-oxygen-scavenger.jpg"
    includeArea: "crown/o2scavenger.html"
  12:
    variantClasses: "crown-corks__item crown-corks__item--last"
    title: "Oxygen Barrier"
    title_variantClasses: "title--large"
    subtitle: "INTERIOR PLASTIC LINER"
    counter: "04"
    body: "A liner profile that actually acts as a barrier to any external contamination such as odor and oxygen ingress into the glass bottle."
    id: "oxygen-barrier-interior"
    group: "interior-liner"
    layout: "layout-two-column"
    mobileImage: "/images/corks/Interior-oxygen-barrier.jpg"
    includeArea: "crown/o2barrier.html"
el:
  production:
    title: "Ελληνικα State of the art plant"
    subtitle: "ΕλληνικαPRODUCTION SITE"
    body: "Ελληνικαbla bla"
    image: http://lorempixel.com/400/200/sports/1

  facilites:
    title: "ΕλληνικαProduction Process"
    subtitle: "Ελληνικα FACILITIES"
    body: "Ελληνικα bla bla BLLMA"
    image: http://lorempixel.com/400/200/sports/2
...
